name: deploy to lambda
on:
  push:
    branches:
    - main
jobs:
  deploy-lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install requirements
        run: |
          pip install -r requirements.txt -t .
      - name: zip
        run: ls
  
